# Specify Base Image
FROM node:alpine as build

# Set working dir
WORKDIR /app

# add node modules to path
ENV PATH /app/node_modules/.bin:$PATH

# Install Dependencies
COPY ./package.json ./
RUN npm --upgrade
RUN npm install yarn
RUN yarn install
COPY . ./
RUN yarn build

# Production Environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]